// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.1
// source: like.proto

package likepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LikeService_ThumbUp_FullMethodName               = "/like.LikeService/ThumbUp"
	LikeService_CancelThumbUp_FullMethodName         = "/like.LikeService/CancelThumbUp"
	LikeService_PageQueryUserLikeList_FullMethodName = "/like.LikeService/PageQueryUserLikeList"
	LikeService_HasLike_FullMethodName               = "/like.LikeService/HasLike"
	LikeService_BatchLikeStatus_FullMethodName       = "/like.LikeService/BatchLikeStatus"
)

// LikeServiceClient is the client API for LikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LikeServiceClient interface {
	ThumbUp(ctx context.Context, in *ThumbUpRequest, opts ...grpc.CallOption) (*ThumbUpResponse, error)
	CancelThumbUp(ctx context.Context, in *CancelThumbUpRequest, opts ...grpc.CallOption) (*CancelThumbUpResponse, error)
	PageQueryUserLikeList(ctx context.Context, in *PageQueryUserLikeListRequest, opts ...grpc.CallOption) (*PageQueryUserLikeListResponse, error)
	HasLike(ctx context.Context, in *HasArticleLikeRequest, opts ...grpc.CallOption) (*HasArticleLikeResponse, error)
	BatchLikeStatus(ctx context.Context, in *BatchCommentLikeStatusRequest, opts ...grpc.CallOption) (*BatchLikeStatusResponse, error)
}

type likeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLikeServiceClient(cc grpc.ClientConnInterface) LikeServiceClient {
	return &likeServiceClient{cc}
}

func (c *likeServiceClient) ThumbUp(ctx context.Context, in *ThumbUpRequest, opts ...grpc.CallOption) (*ThumbUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThumbUpResponse)
	err := c.cc.Invoke(ctx, LikeService_ThumbUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) CancelThumbUp(ctx context.Context, in *CancelThumbUpRequest, opts ...grpc.CallOption) (*CancelThumbUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelThumbUpResponse)
	err := c.cc.Invoke(ctx, LikeService_CancelThumbUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) PageQueryUserLikeList(ctx context.Context, in *PageQueryUserLikeListRequest, opts ...grpc.CallOption) (*PageQueryUserLikeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageQueryUserLikeListResponse)
	err := c.cc.Invoke(ctx, LikeService_PageQueryUserLikeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) HasLike(ctx context.Context, in *HasArticleLikeRequest, opts ...grpc.CallOption) (*HasArticleLikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasArticleLikeResponse)
	err := c.cc.Invoke(ctx, LikeService_HasLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *likeServiceClient) BatchLikeStatus(ctx context.Context, in *BatchCommentLikeStatusRequest, opts ...grpc.CallOption) (*BatchLikeStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchLikeStatusResponse)
	err := c.cc.Invoke(ctx, LikeService_BatchLikeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LikeServiceServer is the server API for LikeService service.
// All implementations must embed UnimplementedLikeServiceServer
// for forward compatibility.
type LikeServiceServer interface {
	ThumbUp(context.Context, *ThumbUpRequest) (*ThumbUpResponse, error)
	CancelThumbUp(context.Context, *CancelThumbUpRequest) (*CancelThumbUpResponse, error)
	PageQueryUserLikeList(context.Context, *PageQueryUserLikeListRequest) (*PageQueryUserLikeListResponse, error)
	HasLike(context.Context, *HasArticleLikeRequest) (*HasArticleLikeResponse, error)
	BatchLikeStatus(context.Context, *BatchCommentLikeStatusRequest) (*BatchLikeStatusResponse, error)
	mustEmbedUnimplementedLikeServiceServer()
}

// UnimplementedLikeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLikeServiceServer struct{}

func (UnimplementedLikeServiceServer) ThumbUp(context.Context, *ThumbUpRequest) (*ThumbUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ThumbUp not implemented")
}
func (UnimplementedLikeServiceServer) CancelThumbUp(context.Context, *CancelThumbUpRequest) (*CancelThumbUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelThumbUp not implemented")
}
func (UnimplementedLikeServiceServer) PageQueryUserLikeList(context.Context, *PageQueryUserLikeListRequest) (*PageQueryUserLikeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PageQueryUserLikeList not implemented")
}
func (UnimplementedLikeServiceServer) HasLike(context.Context, *HasArticleLikeRequest) (*HasArticleLikeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasLike not implemented")
}
func (UnimplementedLikeServiceServer) BatchLikeStatus(context.Context, *BatchCommentLikeStatusRequest) (*BatchLikeStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchLikeStatus not implemented")
}
func (UnimplementedLikeServiceServer) mustEmbedUnimplementedLikeServiceServer() {}

// UnsafeLikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LikeServiceServer will
// result in compilation errors.
type UnsafeLikeServiceServer interface {
	mustEmbedUnimplementedLikeServiceServer()
}

func RegisterLikeServiceServer(s grpc.ServiceRegistrar, srv LikeServiceServer) {
	s.RegisterService(&LikeService_ServiceDesc, srv)
}

func _LikeService_ThumbUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThumbUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).ThumbUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_ThumbUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).ThumbUp(ctx, req.(*ThumbUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_CancelThumbUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelThumbUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).CancelThumbUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_CancelThumbUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).CancelThumbUp(ctx, req.(*CancelThumbUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_PageQueryUserLikeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageQueryUserLikeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).PageQueryUserLikeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_PageQueryUserLikeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).PageQueryUserLikeList(ctx, req.(*PageQueryUserLikeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_HasLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasArticleLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).HasLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_HasLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).HasLike(ctx, req.(*HasArticleLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LikeService_BatchLikeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCommentLikeStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LikeServiceServer).BatchLikeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LikeService_BatchLikeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LikeServiceServer).BatchLikeStatus(ctx, req.(*BatchCommentLikeStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LikeService_ServiceDesc is the grpc.ServiceDesc for LikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "like.LikeService",
	HandlerType: (*LikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ThumbUp", Handler: _LikeService_ThumbUp_Handler},
		{MethodName: "CancelThumbUp", Handler: _LikeService_CancelThumbUp_Handler},
		{MethodName: "PageQueryUserLikeList", Handler: _LikeService_PageQueryUserLikeList_Handler},
		{MethodName: "HasLike", Handler: _LikeService_HasLike_Handler},
		{MethodName: "BatchLikeStatus", Handler: _LikeService_BatchLikeStatus_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "like.proto",
}
