// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: article.proto

// article service
// 与数据库表 `blog_posts` 字段对应的文章 proto 定义

package articlepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage,omitempty"`
	AuthorID      uint64                 `protobuf:"varint,6,opt,name=authorID,proto3" json:"authorID,omitempty"`
	CategoryID    uint64                 `protobuf:"varint,7,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	IsTop         bool                   `protobuf:"varint,8,opt,name=isTop,proto3" json:"isTop,omitempty"`
	ViewCount     uint64                 `protobuf:"varint,9,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	LikeCount     uint64                 `protobuf:"varint,10,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	CommentCount  uint64                 `protobuf:"varint,11,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	CreatedAt     uint64                 `protobuf:"varint,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`      // unix timestamp (seconds)
	UpdatedAt     uint64                 `protobuf:"varint,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`      // unix timestamp (seconds)
	AuthorName    string                 `protobuf:"bytes,14,opt,name=authorName,proto3" json:"authorName,omitempty"`     // 作者昵称，来自 user.name
	AuthorAvatar  string                 `protobuf:"bytes,15,opt,name=authorAvatar,proto3" json:"authorAvatar,omitempty"` // 作者头像，来自 user.avatar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *Article) GetAuthorID() uint64 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *Article) GetCategoryID() uint64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *Article) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *Article) GetViewCount() uint64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Article) GetLikeCount() uint64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Article) GetCommentCount() uint64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Article) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Article) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Article) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *Article) GetAuthorAvatar() string {
	if x != nil {
		return x.AuthorAvatar
	}
	return ""
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorID      uint64                 `protobuf:"varint,1,opt,name=authorID,proto3" json:"authorID,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CoverImage    string                 `protobuf:"bytes,5,opt,name=coverImage,proto3" json:"coverImage,omitempty"`
	CategoryID    uint64                 `protobuf:"varint,6,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	IsTop         bool                   `protobuf:"varint,7,opt,name=isTop,proto3" json:"isTop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetAuthorID() uint64 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *CreateArticleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateArticleRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateArticleRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateArticleRequest) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *CreateArticleRequest) GetCategoryID() uint64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *CreateArticleRequest) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 从 1 开始
	PageSize      uint32                 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListArticlesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorID      uint64                 `protobuf:"varint,2,opt,name=authorID,proto3" json:"authorID,omitempty"` // 请求者用户ID，用于校验是否有权限删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteArticleRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteArticleRequest) GetAuthorID() uint64 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteArticleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMyArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorID      uint64                 `protobuf:"varint,1,opt,name=authorID,proto3" json:"authorID,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyArticlesRequest) Reset() {
	*x = ListMyArticlesRequest{}
	mi := &file_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyArticlesRequest) ProtoMessage() {}

func (x *ListMyArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListMyArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{9}
}

func (x *ListMyArticlesRequest) GetAuthorID() uint64 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *ListMyArticlesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMyArticlesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMyArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyArticlesResponse) Reset() {
	*x = ListMyArticlesResponse{}
	mi := &file_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyArticlesResponse) ProtoMessage() {}

func (x *ListMyArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListMyArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{10}
}

func (x *ListMyArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type ListByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryID    uint64                 `protobuf:"varint,1,opt,name=categoryID,proto3" json:"categoryID,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByCategoryRequest) Reset() {
	*x = ListByCategoryRequest{}
	mi := &file_article_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByCategoryRequest) ProtoMessage() {}

func (x *ListByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{11}
}

func (x *ListByCategoryRequest) GetCategoryID() uint64 {
	if x != nil {
		return x.CategoryID
	}
	return 0
}

func (x *ListByCategoryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListByCategoryRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListByCategoryResponse) Reset() {
	*x = ListByCategoryResponse{}
	mi := &file_article_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListByCategoryResponse) ProtoMessage() {}

func (x *ListByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListByCategoryResponse.ProtoReflect.Descriptor instead.
func (*ListByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{12}
}

func (x *ListByCategoryResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

type SearchArticlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"` // keyword
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesRequest) Reset() {
	*x = SearchArticlesRequest{}
	mi := &file_article_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesRequest) ProtoMessage() {}

func (x *SearchArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesRequest.ProtoReflect.Descriptor instead.
func (*SearchArticlesRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{13}
}

func (x *SearchArticlesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *SearchArticlesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchArticlesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchArticlesResponse) Reset() {
	*x = SearchArticlesResponse{}
	mi := &file_article_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchArticlesResponse) ProtoMessage() {}

func (x *SearchArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchArticlesResponse.ProtoReflect.Descriptor instead.
func (*SearchArticlesResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{14}
}

func (x *SearchArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\aarticle\"\xb5\x03\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x1a\n" +
	"\bauthorID\x18\x06 \x01(\x04R\bauthorID\x12\x1e\n" +
	"\n" +
	"categoryID\x18\a \x01(\x04R\n" +
	"categoryID\x12\x14\n" +
	"\x05isTop\x18\b \x01(\bR\x05isTop\x12\x1c\n" +
	"\tviewCount\x18\t \x01(\x04R\tviewCount\x12\x1c\n" +
	"\tlikeCount\x18\n" +
	" \x01(\x04R\tlikeCount\x12\"\n" +
	"\fcommentCount\x18\v \x01(\x04R\fcommentCount\x12\x1c\n" +
	"\tcreatedAt\x18\f \x01(\x04R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\r \x01(\x04R\tupdatedAt\x12\x1e\n" +
	"\n" +
	"authorName\x18\x0e \x01(\tR\n" +
	"authorName\x12\"\n" +
	"\fauthorAvatar\x18\x0f \x01(\tR\fauthorAvatar\"\xd2\x01\n" +
	"\x14CreateArticleRequest\x12\x1a\n" +
	"\bauthorID\x18\x01 \x01(\x04R\bauthorID\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"coverImage\x18\x05 \x01(\tR\n" +
	"coverImage\x12\x1e\n" +
	"\n" +
	"categoryID\x18\x06 \x01(\x04R\n" +
	"categoryID\x12\x14\n" +
	"\x05isTop\x18\a \x01(\bR\x05isTop\"1\n" +
	"\x15CreateArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"@\n" +
	"\x12GetArticleResponse\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\"E\n" +
	"\x13ListArticlesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\rR\bpageSize\"D\n" +
	"\x14ListArticlesResponse\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles\"B\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bauthorID\x18\x02 \x01(\x04R\bauthorID\"1\n" +
	"\x15DeleteArticleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"c\n" +
	"\x15ListMyArticlesRequest\x12\x1a\n" +
	"\bauthorID\x18\x01 \x01(\x04R\bauthorID\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\rR\bpageSize\"F\n" +
	"\x16ListMyArticlesResponse\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles\"g\n" +
	"\x15ListByCategoryRequest\x12\x1e\n" +
	"\n" +
	"categoryID\x18\x01 \x01(\x04R\n" +
	"categoryID\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\rR\bpageSize\"F\n" +
	"\x16ListByCategoryResponse\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles\"U\n" +
	"\x15SearchArticlesRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\rR\bpageSize\"F\n" +
	"\x16SearchArticlesResponse\x12,\n" +
	"\barticles\x18\x01 \x03(\v2\x10.article.ArticleR\barticles2\xcb\x04\n" +
	"\x0eArticleService\x12P\n" +
	"\rCreateArticle\x12\x1d.article.CreateArticleRequest\x1a\x1e.article.CreateArticleResponse\"\x00\x12G\n" +
	"\n" +
	"GetArticle\x12\x1a.article.GetArticleRequest\x1a\x1b.article.GetArticleResponse\"\x00\x12M\n" +
	"\fListArticles\x12\x1c.article.ListArticlesRequest\x1a\x1d.article.ListArticlesResponse\"\x00\x12S\n" +
	"\x0eListMyArticles\x12\x1e.article.ListMyArticlesRequest\x1a\x1f.article.ListMyArticlesResponse\"\x00\x12S\n" +
	"\x0eListByCategory\x12\x1e.article.ListByCategoryRequest\x1a\x1f.article.ListByCategoryResponse\"\x00\x12S\n" +
	"\x0eSearchArticles\x12\x1e.article.SearchArticlesRequest\x1a\x1f.article.SearchArticlesResponse\"\x00\x12P\n" +
	"\rDeleteArticle\x12\x1d.article.DeleteArticleRequest\x1a\x1e.article.DeleteArticleResponse\"\x00BBZ@backend/gateway/internal/client/rpc/core-rpc/articlepb;articlepbb\x06proto3"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_article_proto_goTypes = []any{
	(*Article)(nil),                // 0: article.Article
	(*CreateArticleRequest)(nil),   // 1: article.CreateArticleRequest
	(*CreateArticleResponse)(nil),  // 2: article.CreateArticleResponse
	(*GetArticleRequest)(nil),      // 3: article.GetArticleRequest
	(*GetArticleResponse)(nil),     // 4: article.GetArticleResponse
	(*ListArticlesRequest)(nil),    // 5: article.ListArticlesRequest
	(*ListArticlesResponse)(nil),   // 6: article.ListArticlesResponse
	(*DeleteArticleRequest)(nil),   // 7: article.DeleteArticleRequest
	(*DeleteArticleResponse)(nil),  // 8: article.DeleteArticleResponse
	(*ListMyArticlesRequest)(nil),  // 9: article.ListMyArticlesRequest
	(*ListMyArticlesResponse)(nil), // 10: article.ListMyArticlesResponse
	(*ListByCategoryRequest)(nil),  // 11: article.ListByCategoryRequest
	(*ListByCategoryResponse)(nil), // 12: article.ListByCategoryResponse
	(*SearchArticlesRequest)(nil),  // 13: article.SearchArticlesRequest
	(*SearchArticlesResponse)(nil), // 14: article.SearchArticlesResponse
}
var file_article_proto_depIdxs = []int32{
	0,  // 0: article.GetArticleResponse.article:type_name -> article.Article
	0,  // 1: article.ListArticlesResponse.articles:type_name -> article.Article
	0,  // 2: article.ListMyArticlesResponse.articles:type_name -> article.Article
	0,  // 3: article.ListByCategoryResponse.articles:type_name -> article.Article
	0,  // 4: article.SearchArticlesResponse.articles:type_name -> article.Article
	1,  // 5: article.ArticleService.CreateArticle:input_type -> article.CreateArticleRequest
	3,  // 6: article.ArticleService.GetArticle:input_type -> article.GetArticleRequest
	5,  // 7: article.ArticleService.ListArticles:input_type -> article.ListArticlesRequest
	9,  // 8: article.ArticleService.ListMyArticles:input_type -> article.ListMyArticlesRequest
	11, // 9: article.ArticleService.ListByCategory:input_type -> article.ListByCategoryRequest
	13, // 10: article.ArticleService.SearchArticles:input_type -> article.SearchArticlesRequest
	7,  // 11: article.ArticleService.DeleteArticle:input_type -> article.DeleteArticleRequest
	2,  // 12: article.ArticleService.CreateArticle:output_type -> article.CreateArticleResponse
	4,  // 13: article.ArticleService.GetArticle:output_type -> article.GetArticleResponse
	6,  // 14: article.ArticleService.ListArticles:output_type -> article.ListArticlesResponse
	10, // 15: article.ArticleService.ListMyArticles:output_type -> article.ListMyArticlesResponse
	12, // 16: article.ArticleService.ListByCategory:output_type -> article.ListByCategoryResponse
	14, // 17: article.ArticleService.SearchArticles:output_type -> article.SearchArticlesResponse
	8,  // 18: article.ArticleService.DeleteArticle:output_type -> article.DeleteArticleResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
