syntax = "proto3";

package auth;

option go_package = "gateway/internal/client/rpc/core-rpc/authpb;authpb";



message UserInfo {
  uint64 id = 1;
  string username = 2;
  string email = 3;
  string phone = 4;
  string avatar = 5;
  string sex = 6;
  uint32 age = 7;
  string role = 8;
  string status = 9;
  uint64 auth_version = 10;
}

message RegisterRequest {
  string username = 1;
  string email = 2;
  string password = 3;
  string confirm_password = 4;
  string email_code = 5;
  string phone = 6;
  string avatar = 7;
  string sex = 8;
  uint32 age = 9;
}

message RegisterResponse {
  bool success = 1;
  UserInfo user = 2;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message EmailLoginRequest {
  string email = 1;
  string code = 2;
}

message LoginResponse {
  UserInfo user = 1;
}

message LogoutRequest {
  string refresh_token = 1;
}

message LogoutResponse {
  bool success = 1;
}

service AuthService {
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc Login(LoginRequest) returns (LoginResponse);
  rpc EmailLogin(EmailLoginRequest) returns (LoginResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
}
