syntax = "proto3";

package comment;
option go_package = "gateway/internal/client/rpc/core-rpc/commentpb;commentpb";

message CommentInfo {
  uint64 id = 1;
  uint64 articleId = 2;
  uint64 userId = 3;
  uint64 parentId = 4;
  uint64 rootId = 5;
  uint64 replyToId = 6;
  string content = 8;
  uint32 likeCount = 9;
  uint32 childCount = 10;
  string createdAt = 11;
  string userName = 12;
  string userAvatar = 13;
  bool isLiked = 14; // 当前用户是否点过赞
}

message CreateCommentReq {
  uint64 articleId = 1;
  uint64 userId = 2;
  string content = 3;
}
message CreateCommentResp {
  bool success = 1;
}

message CreateReplyReq {
  uint64 rootId = 1;       // 一级评论ID
  uint64 userId = 2;
  uint64 replyToId = 3;    // @回复目标用户
  string content = 4;
  uint64 articleId = 5;     // 文章ID
}
message CreateReplyResp {
  bool success =1;
}

message DeleteCommentReq {
  uint64 id = 1;
  uint64 userId = 2;
}
message DeleteCommentResp {
  bool success =1;
}

message GetArticleCommentsReq {
  uint64 articleId = 1;
  int32 page = 2;
  int32 size = 3;
}
message GetArticleCommentsResp {
  repeated CommentInfo comments = 1;
  int32 page = 2;
  int32 size = 3;
}

message GetCommentRepliesReq {
  uint64 parentId = 1;
  int32 page = 2;
  int32 size = 3;
}
message GetCommentRepliesResp {
  repeated CommentInfo replies = 1;
  int32 page = 2;
  int32 size = 3;
}

service CommentService {
  rpc CreateComment(CreateCommentReq) returns (CreateCommentResp) {}
  rpc CreateReply(CreateReplyReq) returns (CreateReplyResp) {}
  rpc DeleteComment(DeleteCommentReq) returns (DeleteCommentResp) {}
  rpc GetArticleComments(GetArticleCommentsReq) returns (GetArticleCommentsResp) {}
  rpc GetCommentReplies(GetCommentRepliesReq) returns (GetCommentRepliesResp) {}
}
