syntax = "proto3";

// provide user like service
// 1. add like

import "article.proto";

package like;
//import "idl/validate/validate.proto";
option go_package = "gateway/internal/client/rpc/core-rpc/likepb;likepb";

// 1.点赞操作 和 取消点赞
message ThumbUpRequest {
  uint64 userID = 1;
  string objectType = 2;
  uint64 objectID = 3;
}
message ThumbUpResponse {
  bool success = 1;
}

message CancelThumbUpRequest {
  uint64 userID = 1;
  string objectType = 2;
  uint64 objectID = 3;
}
message CancelThumbUpResponse {
  bool success = 1;
}

message PageQueryUserLikeListRequest {
  uint64 userID = 1;
  string objectType = 2;
  int32 page = 3;
  int32 pageSize = 4;
}
message PageQueryUserLikeListResponse {
  repeated article.Article articles = 1;
  int64 total = 2;
}

message HasLikeRequest {
  uint64 userID = 1;
  string objectType = 2;
  uint64 objectID = 3;
}
message HasLikeResponse {
  bool isLiked = 1;
}

service LikeService {
  rpc ThumbUp(ThumbUpRequest) returns (ThumbUpResponse) {};
  rpc CancelThumbUp(CancelThumbUpRequest) returns (CancelThumbUpResponse) {};
  rpc PageQueryUserLikeList(PageQueryUserLikeListRequest) returns (PageQueryUserLikeListResponse) {};
  rpc HasLike(HasLikeRequest) returns (HasLikeResponse) {};
}