// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: comment.proto

package commentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ArticleId     uint64                 `protobuf:"varint,2,opt,name=articleId,proto3" json:"articleId,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	ParentId      uint64                 `protobuf:"varint,4,opt,name=parentId,proto3" json:"parentId,omitempty"`
	RootId        uint64                 `protobuf:"varint,5,opt,name=rootId,proto3" json:"rootId,omitempty"`
	ReplyToId     uint64                 `protobuf:"varint,6,opt,name=replyToId,proto3" json:"replyToId,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     uint32                 `protobuf:"varint,9,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	ChildCount    uint32                 `protobuf:"varint,10,opt,name=childCount,proto3" json:"childCount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UserName      string                 `protobuf:"bytes,12,opt,name=userName,proto3" json:"userName,omitempty"`
	UserAvatar    string                 `protobuf:"bytes,13,opt,name=userAvatar,proto3" json:"userAvatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentInfo) Reset() {
	*x = CommentInfo{}
	mi := &file_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentInfo) ProtoMessage() {}

func (x *CommentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentInfo.ProtoReflect.Descriptor instead.
func (*CommentInfo) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{0}
}

func (x *CommentInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommentInfo) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *CommentInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommentInfo) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CommentInfo) GetRootId() uint64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CommentInfo) GetReplyToId() uint64 {
	if x != nil {
		return x.ReplyToId
	}
	return 0
}

func (x *CommentInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentInfo) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *CommentInfo) GetChildCount() uint32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *CommentInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CommentInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CommentInfo) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

type CreateCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint64                 `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentReq) Reset() {
	*x = CreateCommentReq{}
	mi := &file_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentReq) ProtoMessage() {}

func (x *CreateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentReq.ProtoReflect.Descriptor instead.
func (*CreateCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentReq) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *CreateCommentReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResp) Reset() {
	*x = CreateCommentResp{}
	mi := &file_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResp) ProtoMessage() {}

func (x *CreateCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResp.ProtoReflect.Descriptor instead.
func (*CreateCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateReplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        uint64                 `protobuf:"varint,1,opt,name=rootId,proto3" json:"rootId,omitempty"` // 一级评论ID
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ReplyToId     uint64                 `protobuf:"varint,3,opt,name=replyToId,proto3" json:"replyToId,omitempty"` // @回复目标用户
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ArticleId     uint64                 `protobuf:"varint,5,opt,name=articleId,proto3" json:"articleId,omitempty"` // 文章ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyReq) Reset() {
	*x = CreateReplyReq{}
	mi := &file_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyReq) ProtoMessage() {}

func (x *CreateReplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyReq.ProtoReflect.Descriptor instead.
func (*CreateReplyReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReplyReq) GetRootId() uint64 {
	if x != nil {
		return x.RootId
	}
	return 0
}

func (x *CreateReplyReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateReplyReq) GetReplyToId() uint64 {
	if x != nil {
		return x.ReplyToId
	}
	return 0
}

func (x *CreateReplyReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReplyReq) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

type CreateReplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReplyResp) Reset() {
	*x = CreateReplyResp{}
	mi := &file_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReplyResp) ProtoMessage() {}

func (x *CreateReplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReplyResp.ProtoReflect.Descriptor instead.
func (*CreateReplyResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReplyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteCommentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReq) Reset() {
	*x = DeleteCommentReq{}
	mi := &file_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReq) ProtoMessage() {}

func (x *DeleteCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReq.ProtoReflect.Descriptor instead.
func (*DeleteCommentReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteCommentReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteCommentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResp) Reset() {
	*x = DeleteCommentResp{}
	mi := &file_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResp) ProtoMessage() {}

func (x *DeleteCommentResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResp.ProtoReflect.Descriptor instead.
func (*DeleteCommentResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCommentResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetArticleCommentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint64                 `protobuf:"varint,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleCommentsReq) Reset() {
	*x = GetArticleCommentsReq{}
	mi := &file_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleCommentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleCommentsReq) ProtoMessage() {}

func (x *GetArticleCommentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleCommentsReq.ProtoReflect.Descriptor instead.
func (*GetArticleCommentsReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{7}
}

func (x *GetArticleCommentsReq) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *GetArticleCommentsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetArticleCommentsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetArticleCommentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*CommentInfo         `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleCommentsResp) Reset() {
	*x = GetArticleCommentsResp{}
	mi := &file_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleCommentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleCommentsResp) ProtoMessage() {}

func (x *GetArticleCommentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleCommentsResp.ProtoReflect.Descriptor instead.
func (*GetArticleCommentsResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{8}
}

func (x *GetArticleCommentsResp) GetComments() []*CommentInfo {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetArticleCommentsResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetArticleCommentsResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetCommentRepliesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      uint64                 `protobuf:"varint,1,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRepliesReq) Reset() {
	*x = GetCommentRepliesReq{}
	mi := &file_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRepliesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRepliesReq) ProtoMessage() {}

func (x *GetCommentRepliesReq) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRepliesReq.ProtoReflect.Descriptor instead.
func (*GetCommentRepliesReq) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{9}
}

func (x *GetCommentRepliesReq) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *GetCommentRepliesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentRepliesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetCommentRepliesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*CommentInfo         `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRepliesResp) Reset() {
	*x = GetCommentRepliesResp{}
	mi := &file_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRepliesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRepliesResp) ProtoMessage() {}

func (x *GetCommentRepliesResp) ProtoReflect() protoreflect.Message {
	mi := &file_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRepliesResp.ProtoReflect.Descriptor instead.
func (*GetCommentRepliesResp) Descriptor() ([]byte, []int) {
	return file_comment_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommentRepliesResp) GetReplies() []*CommentInfo {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *GetCommentRepliesResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentRepliesResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_comment_proto protoreflect.FileDescriptor

const file_comment_proto_rawDesc = "" +
	"\n" +
	"\rcomment.proto\x12\acomment\"\xd7\x02\n" +
	"\vCommentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tarticleId\x18\x02 \x01(\x04R\tarticleId\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bparentId\x18\x04 \x01(\x04R\bparentId\x12\x16\n" +
	"\x06rootId\x18\x05 \x01(\x04R\x06rootId\x12\x1c\n" +
	"\treplyToId\x18\x06 \x01(\x04R\treplyToId\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1c\n" +
	"\tlikeCount\x18\t \x01(\rR\tlikeCount\x12\x1e\n" +
	"\n" +
	"childCount\x18\n" +
	" \x01(\rR\n" +
	"childCount\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\buserName\x18\f \x01(\tR\buserName\x12\x1e\n" +
	"\n" +
	"userAvatar\x18\r \x01(\tR\n" +
	"userAvatar\"b\n" +
	"\x10CreateCommentReq\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x04R\tarticleId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"-\n" +
	"\x11CreateCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x96\x01\n" +
	"\x0eCreateReplyReq\x12\x16\n" +
	"\x06rootId\x18\x01 \x01(\x04R\x06rootId\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\x12\x1c\n" +
	"\treplyToId\x18\x03 \x01(\x04R\treplyToId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1c\n" +
	"\tarticleId\x18\x05 \x01(\x04R\tarticleId\"+\n" +
	"\x0fCreateReplyResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\":\n" +
	"\x10DeleteCommentReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x04R\x06userId\"-\n" +
	"\x11DeleteCommentResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"]\n" +
	"\x15GetArticleCommentsReq\x12\x1c\n" +
	"\tarticleId\x18\x01 \x01(\x04R\tarticleId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"r\n" +
	"\x16GetArticleCommentsResp\x120\n" +
	"\bcomments\x18\x01 \x03(\v2\x14.comment.CommentInfoR\bcomments\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"Z\n" +
	"\x14GetCommentRepliesReq\x12\x1a\n" +
	"\bparentId\x18\x01 \x01(\x04R\bparentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"o\n" +
	"\x15GetCommentRepliesResp\x12.\n" +
	"\areplies\x18\x01 \x03(\v2\x14.comment.CommentInfoR\areplies\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size2\x97\x03\n" +
	"\x0eCommentService\x12H\n" +
	"\rCreateComment\x12\x19.comment.CreateCommentReq\x1a\x1a.comment.CreateCommentResp\"\x00\x12B\n" +
	"\vCreateReply\x12\x17.comment.CreateReplyReq\x1a\x18.comment.CreateReplyResp\"\x00\x12H\n" +
	"\rDeleteComment\x12\x19.comment.DeleteCommentReq\x1a\x1a.comment.DeleteCommentResp\"\x00\x12W\n" +
	"\x12GetArticleComments\x12\x1e.comment.GetArticleCommentsReq\x1a\x1f.comment.GetArticleCommentsResp\"\x00\x12T\n" +
	"\x11GetCommentReplies\x12\x1d.comment.GetCommentRepliesReq\x1a\x1e.comment.GetCommentRepliesResp\"\x00B:Z8gateway/internal/client/rpc/core-rpc/commentpb;commentpbb\x06proto3"

var (
	file_comment_proto_rawDescOnce sync.Once
	file_comment_proto_rawDescData []byte
)

func file_comment_proto_rawDescGZIP() []byte {
	file_comment_proto_rawDescOnce.Do(func() {
		file_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)))
	})
	return file_comment_proto_rawDescData
}

var file_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_comment_proto_goTypes = []any{
	(*CommentInfo)(nil),            // 0: comment.CommentInfo
	(*CreateCommentReq)(nil),       // 1: comment.CreateCommentReq
	(*CreateCommentResp)(nil),      // 2: comment.CreateCommentResp
	(*CreateReplyReq)(nil),         // 3: comment.CreateReplyReq
	(*CreateReplyResp)(nil),        // 4: comment.CreateReplyResp
	(*DeleteCommentReq)(nil),       // 5: comment.DeleteCommentReq
	(*DeleteCommentResp)(nil),      // 6: comment.DeleteCommentResp
	(*GetArticleCommentsReq)(nil),  // 7: comment.GetArticleCommentsReq
	(*GetArticleCommentsResp)(nil), // 8: comment.GetArticleCommentsResp
	(*GetCommentRepliesReq)(nil),   // 9: comment.GetCommentRepliesReq
	(*GetCommentRepliesResp)(nil),  // 10: comment.GetCommentRepliesResp
}
var file_comment_proto_depIdxs = []int32{
	0,  // 0: comment.GetArticleCommentsResp.comments:type_name -> comment.CommentInfo
	0,  // 1: comment.GetCommentRepliesResp.replies:type_name -> comment.CommentInfo
	1,  // 2: comment.CommentService.CreateComment:input_type -> comment.CreateCommentReq
	3,  // 3: comment.CommentService.CreateReply:input_type -> comment.CreateReplyReq
	5,  // 4: comment.CommentService.DeleteComment:input_type -> comment.DeleteCommentReq
	7,  // 5: comment.CommentService.GetArticleComments:input_type -> comment.GetArticleCommentsReq
	9,  // 6: comment.CommentService.GetCommentReplies:input_type -> comment.GetCommentRepliesReq
	2,  // 7: comment.CommentService.CreateComment:output_type -> comment.CreateCommentResp
	4,  // 8: comment.CommentService.CreateReply:output_type -> comment.CreateReplyResp
	6,  // 9: comment.CommentService.DeleteComment:output_type -> comment.DeleteCommentResp
	8,  // 10: comment.CommentService.GetArticleComments:output_type -> comment.GetArticleCommentsResp
	10, // 11: comment.CommentService.GetCommentReplies:output_type -> comment.GetCommentRepliesResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_comment_proto_init() }
func file_comment_proto_init() {
	if File_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_proto_rawDesc), len(file_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_proto_goTypes,
		DependencyIndexes: file_comment_proto_depIdxs,
		MessageInfos:      file_comment_proto_msgTypes,
	}.Build()
	File_comment_proto = out.File
	file_comment_proto_goTypes = nil
	file_comment_proto_depIdxs = nil
}
