// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/gateway/internal/client/rpc"
	"backend/gateway/internal/config"
	"backend/gateway/internal/facade/controller"
	"backend/gateway/internal/server"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*server.Server, error) {
	client, err := rpc.NewRPCClient(cfg)
	if err != nil {
		return nil, err
	}
	healthController := controller.NewHealthController(client)
	serverServer, err := server.NewServer(cfg, client, healthController)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
