// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/internal/application"
	"gateway/internal/client/http"
	"gateway/internal/client/rpc"
	"gateway/internal/config"
	"gateway/internal/facade"
	"gateway/internal/facade/controller"
	"gateway/internal/infras/api/llm"
	"gateway/internal/infras/cache"
	"gateway/internal/infras/clog"
	"gateway/internal/infras/repo"
	"gateway/internal/infras/storage"
	"gateway/internal/server"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*server.Server, error) {
	client, err := rpc.NewRPCClient(cfg)
	if err != nil {
		return nil, err
	}
	dbClient, err := repo.NewDBClient(cfg)
	if err != nil {
		return nil, err
	}
	cacheClient := cache.NewClient(cfg)
	healthController := controller.NewHealthController(client)
	aiChatRepo := repo.NewAiChatRepo(dbClient)
	pyClient := http.NewHTTPClient(cfg)
	llmClient, err := llm.NewClient(cfg)
	if err != nil {
		return nil, err
	}
	aiChatService := application.NewAiChatService(cfg, aiChatRepo, pyClient, llmClient)
	aiChatController := controller.NewAiChatController(aiChatService)
	userController := controller.NewUserController(client)
	categoryController := controller.NewCategoryController(client)
	articleController := controller.NewArticleController(client)
	storageClient, err := storage.NewClient(cfg)
	if err != nil {
		return nil, err
	}
	storageService := application.NewStorageService(cfg, storageClient)
	storageController := controller.NewStorageController(storageService)
	commentController := controller.NewCommentController(client)
	likeController := controller.NewLikeController(client)
	log, err := clog.NewLog(cfg)
	if err != nil {
		return nil, err
	}
	authController := controller.NewAuthController(client, cfg, log)
	engine := facade.New(cfg, healthController, aiChatController, userController, categoryController, articleController, storageController, commentController, likeController, authController)
	serverServer, err := server.NewServer(cfg, client, dbClient, cacheClient, engine)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
