// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend/gateway/internal/application"
	"backend/gateway/internal/client/http"
	"backend/gateway/internal/client/rpc"
	"backend/gateway/internal/config"
	"backend/gateway/internal/facade/controller"
	"backend/gateway/internal/facade/router"
	"backend/gateway/internal/infras/api/llm"
	"backend/gateway/internal/infras/cache"
	"backend/gateway/internal/infras/repo"
	"backend/gateway/internal/server"
)

// Injectors from wire.go:

func InitializeServer(cfg *config.Config) (*server.Server, error) {
	client, err := rpc.NewRPCClient(cfg)
	if err != nil {
		return nil, err
	}
	dbClient, err := repo.NewDBClient(cfg)
	if err != nil {
		return nil, err
	}
	cacheClient := cache.NewClient(cfg)
	aiChatRepo := repo.NewAiChatRepo(dbClient)
	pyClient := http.NewHTTPClient(cfg)
	llmClient, err := llm.NewClient(cfg)
	if err != nil {
		return nil, err
	}
	aiChatService := application.NewAiChatService(cfg, aiChatRepo, pyClient, llmClient)
	healthController := controller.NewHealthController(client)
	aiChatController := controller.NewAiChatController(aiChatService)
	engine := router.New(cfg, healthController, aiChatController)
	serverServer, err := server.NewServer(cfg, client, dbClient, cacheClient, engine)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
